version = 0.1

[default.deploy.parameters]
stack_name = "asicMargin-app"
s3_bucket = "asic-margin-artifacts"
s3_prefix = "asicMargin-app"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
